### ISSUE TITLE
e-Statは最大100000行データしか撮れません

### ISSUE THREAD

**Issue by Alalalalaki** [sinhrks/japandas#58]
Hi
Thank you very much for your package. This is the only python package I find can directly read e-Stat data. 
But the problem here is that I find for some large dataset I can only get 100000 rows for most. 

---
Update:
Sorry I find I ask the wrong question because the data limit is an issue with e-Stat itself. So the question changes to that can I add some specific parameters other than statsDataId in jpd.DataReader() ?

**Comment by sinhrks** [comment]
Thank you for the report. Maybe we should provide `limit` parameter in the request. Is it possible for you to tell me dataset name which has 100000 rows (to confirm the behavior) ?

https://www.e-stat.go.jp/api/api-info/e-stat-manual

**Comment by Alalalalaki** [comment]
@sinhrks Thank you for your reply. There are quite a lot of dataset that has over 100000 rows, e.g. 生産・出荷集中度調査 / 累積生産集中度（長期時系列データ）(statsDataId=0003280394). 

One way I find to solve this problem is to specify the "cat01"/"cat02"/"cat03" (which can be found in meta information) when using API to request data and then to loop for all the categories. Thus it will be great appreciated if you can add the function of parameter-specification to jpd.DataReader().

**Comment by sinhrks** [comment]
I've fixed the issue and going to release new version (0.5.1).

e-stat `limit` kw doesn't work for more than 100,000 records. Thus, you should specify `startPosition` kw.

https://japandas.readthedocs.io/en/latest/jpdatareader.html#e-stat-api

**Comment by Alalalalaki** [comment]
@sinhrks Sorry, I didn't notice your comment. I solved the 100,000 limit by divid the data into several pieces based on the meta code of the category like industry and scale. But your approach is just better. Great job.
